name: Continuous Delivery
on:
  push:
    tags:
    - "v[0-9]+.[0-9]+.[0-9]+"
jobs:
  pack-and-push:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Extract VERSION
      run: echo "VERSION=${GITHUB_REF/refs\/tags\/v/}" >> $GITHUB_ENV
      shell: bash
    - name: Setup .NET Core 3.1 SDK
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '3.1.x'
    - name: Setup .NET 5.0 SDK
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '5.0.x'
    - name: Restore
      run: dotnet restore
    - name: Build
      run: dotnet build --configuration Release --no-restore
    - name: Pack
      run: dotnet pack --configuration Release --no-build
    - name: NuGet Push Lib.AspNetCore.Security
      run: dotnet nuget push src/Lib.AspNetCore.Security/bin/Release/Lib.AspNetCore.Security.${VERSION}.nupkg --source https://api.nuget.org/v3/index.json --api-key ${NUGET_API_KEY}
      shell: bash
      env:
        NUGET_API_KEY: ${{ secrets.NUGET_API_KEY }}
    - name: NuGet Push Lib.AspNetCore.Mvc.Security
      run: dotnet nuget push src/Lib.AspNetCore.Mvc.Security/bin/Release/Lib.AspNetCore.Mvc.Security.${VERSION}.nupkg --source https://api.nuget.org/v3/index.json --api-key ${NUGET_API_KEY}
      shell: bash
      env:
        NUGET_API_KEY: ${{ secrets.NUGET_API_KEY }}